# Generated by Django 3.2.7 on 2021-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
