# Generated by Django 3.2.7 on 2021-10-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_message_parsed'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoraMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deveui', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('locOrigin', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('radius', models.DecimalField(decimal_places=6, max_digits=12)),
                ('locAccuracy', models.DecimalField(decimal_places=6, max_digits=12)),
                ('locPrecision', models.DecimalField(decimal_places=6, max_digits=12)),
                ('locTime', models.DateTimeField()),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.message')),
            ],
        ),
        migrations.CreateModel(
            name='GpsTrackerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deveui', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('payload', models.CharField(max_length=1000)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('alarm', models.BooleanField(default=False)),
                ('battery', models.DecimalField(decimal_places=3, max_digits=5)),
                ('led_activity', models.BooleanField(default=False)),
                ('movement_detection', models.IntegerField()),
                ('roll', models.DecimalField(decimal_places=3, max_digits=5)),
                ('pitch', models.DecimalField(decimal_places=3, max_digits=5)),
                ('altitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('hdop', models.DecimalField(decimal_places=3, max_digits=5)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iot.message')),
            ],
        ),
    ]
