# Generated by Django 3.2.7 on 2021-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_gpstrackermessage_loramessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpstrackermessage',
            name='battery_perc',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gpstrackermessage',
            name='altitude',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gpstrackermessage',
            name='battery',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='gpstrackermessage',
            name='hdop',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gpstrackermessage',
            name='pitch',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gpstrackermessage',
            name='roll',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
